# Generated by Django 2.0.7 on 2019-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255)),
                ('op1', models.TextField(max_length=255)),
                ('op2', models.TextField(max_length=255)),
                ('op3', models.TextField(max_length=255)),
                ('op4', models.TextField(max_length=255)),
            ],
        ),
    ]
