# Generated by Django 2.0.7 on 2019-08-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('op1', models.TextField(blank=True, max_length=255)),
                ('op2', models.TextField(blank=True, max_length=255)),
                ('op3', models.TextField(blank=True, max_length=255)),
                ('op4', models.TextField(blank=True, max_length=255)),
                ('ans', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Random_No',
            fields=[
                ('random', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_no', models.IntegerField(unique=True)),
                ('normal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Random_No')),
            ],
        ),
    ]
