# Generated by Django 2.0.7 on 2019-08-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190807_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='start',
            name='id',
        ),
        migrations.AlterField(
            model_name='start',
            name='student_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='show',
            name='studentno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Start'),
        ),
        migrations.AddField(
            model_name='identify',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Start'),
        ),
        migrations.AddField(
            model_name='identify',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
