# Generated by Django 2.0.7 on 2019-08-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190811_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='random_string',
            field=models.OneToOneField(default='dealdone', on_delete=django.db.models.deletion.CASCADE, to='app.Random'),
        ),
    ]
